### ISSUE TITLE
Sqrt

### ISSUE THREAD

**Issue by samuellieberman** [Ratologist/CS-HU-271-Team-3#19]
As a user, I would like to square root numbers so that I can the square root from the calculator.

Acceptance Criteria: Reliably compute the square root of a number.

Unary symbol.  Note: for now, parentheses shouldn't be included in beforeSymbol() and afterSymbol().

**Comment by Kylestricken** [comment]
As a user, I would like to square root numbers so that I can the square root from the calculator.

Acceptance Criteria: Reliably compute the square root of a number.
