### ISSUE TITLE
Multiplication

### ISSUE THREAD

**Issue by samuellieberman** [Ratologist/CS-HU-271-Team-3#9]
As a user I would like to use the multiplication function so that I can multiple numbers.

Acceptance Criteria: Consistently multiply two numbers and get the correct result.

**Comment by Kylestricken** [comment]
As a user I would like to use the multiplication function so that I can multiple numbers.

**Comment by Kylestricken** [comment]
Acceptance Criteria: Consistently multiply two numbers and get the correct result.
